# Generated by Django 5.0.4 on 2024-10-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Наименование категории товара')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug для url')),
                ('desctiption', models.TextField(blank=True, max_length=500, null=True, verbose_name='description (описание страницы)')),
                ('keywords', models.TextField(blank=True, help_text='через запятую', max_length=500, null=True, verbose_name='keywords')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Наименование')),
                ('about', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Краткое описание')),
                ('about_big', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Большое описание')),
                ('cost', models.IntegerField(default=100, verbose_name='Цена')),
                ('in_top', models.BooleanField(default=False, verbose_name='В топе')),
                ('desctiption', models.TextField(max_length=500, verbose_name='description (описание страницы)')),
                ('keywords', models.TextField(help_text='через запятую', max_length=500, verbose_name='keywords')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='slug для url')),
                ('category', models.ManyToManyField(null=True, related_name='products', to='products.categories', verbose_name='Вид товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
