# Generated by Django 5.0.4 on 2024-10-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_category_productsimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='cost',
            new_name='price',
        ),
    ]
