# Generated by Django 5.0.4 on 2024-10-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_characteristics_characteristicsmiddlemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='keywords',
        ),
    ]
