# Generated by Django 5.1.2 on 2024-11-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rang',
            field=models.IntegerField(default=1, verbose_name='Порядок вывода'),
        ),
        migrations.AddField(
            model_name='productsimages',
            name='about',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Краткое описание'),
        ),
    ]
