# Generated by Django 5.0.4 on 2025-01-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_products_rang_productsimages_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Наименование производителя')),
                ('image', models.ImageField(blank=True, upload_to='firmsimages', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug для url')),
                ('desctiption', models.TextField(blank=True, max_length=500, null=True, verbose_name='description (описание страницы)')),
            ],
            options={
                'verbose_name': 'Фирма (производитель)',
                'verbose_name_plural': 'Фирмы (производители)',
            },
        ),
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, upload_to='categoryimages', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='categories',
            name='firm',
            field=models.ManyToManyField(related_name='firm', to='products.firms', verbose_name='Фирма'),
        ),
    ]
