# Generated by Django 5.0.4 on 2024-11-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_products_rang'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsimages',
            name='about',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Краткое описание'),
        ),
    ]
