# Generated by Django 5.1.2 on 2025-01-25 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_categories_image_firms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firms',
            name='category',
        ),
        migrations.AddField(
            model_name='categories',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firm', to='products.firms', verbose_name='Фирма'),
        ),
    ]
