# Generated by Django 5.1.2 on 2025-03-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_orders_obtains'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='use_in_feed',
            field=models.BooleanField(default=False, verbose_name='Использовать в Яндекс фиде'),
        ),
    ]
