# Generated by Django 5.0.4 on 2025-03-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_orders_obtains'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='use_in_feed',
            field=models.BooleanField(default=False, verbose_name='Использовать в Яндекс фиде'),
        ),
        migrations.AlterField(
            model_name='obtains',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
