# Generated by Django 5.0.4 on 2025-04-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_products_use_in_feed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firms',
            options={'ordering': ['rang'], 'verbose_name': 'Фирма (производитель)', 'verbose_name_plural': 'Фирмы (производители)'},
        ),
        migrations.AddField(
            model_name='firms',
            name='rang',
            field=models.IntegerField(default=1, verbose_name='Порядок вывода'),
        ),
    ]
