# Generated by Django 5.0.4 on 2025-04-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_firms_options_firms_rang'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_called',
            field=models.BooleanField(default=False, verbose_name='Запрос обработан'),
        ),
    ]
