# Generated by Django 5.0.4 on 2025-09-30 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_firms_options_firms_rang_orders_is_called'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicsmiddlemodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.products', verbose_name='Товар'),
        ),
    ]
