# Generated by Django 5.0.4 on 2026-01-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_characteristicsmiddlemodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='like_what',
            field=models.ManyToManyField(blank=True, to='products.products', verbose_name='Сопутствующие товары'),
        ),
    ]
