# Generated by Django 5.0.4 on 2026-06-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_products_like_what'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='orders',
            name='comment_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата комментария'),
        ),
    ]
