# Generated by Django 5.0.4 on 2026-07-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_orders_comment_orders_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.FloatField(default=4.5, help_text='Рейтинг товара', verbose_name='Рейтинг'),
        ),
    ]
