# Generated by Django 5.0.4 on 2026-07-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_products_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.7, help_text='Рейтинг товара', max_digits=2, verbose_name='Рейтинг'),
        ),
    ]
