# Generated by Django 5.0.4 on 2024-10-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Наименование')),
                ('text', models.CharField(max_length=180, verbose_name='Текст (выводимый)')),
                ('link', models.CharField(help_text='Например https://t.me/link', max_length=180, verbose_name='Ссылка')),
                ('code', models.CharField(default='fa-phone', help_text='Например fa-shower https://fontawesome.com/v4/icon/question', max_length=180, verbose_name='Код иконки')),
                ('show_in_top', models.BooleanField(default=False, verbose_name='Выводить сверху')),
                ('show_in_bottom', models.BooleanField(default=False, verbose_name='Выводить снизу')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
