# Generated by Django 5.0.4 on 2024-10-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_alter_contacts_options_contacts_ranc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=80, verbose_name='Номер телефона')),
                ('dateandtame', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('product', models.CharField(max_length=800, verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ обратного звонка',
                'verbose_name_plural': 'Заказы обратного звонка',
            },
        ),
    ]
