# Generated by Django 5.0.4 on 2025-04-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_callrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='is_called',
            field=models.BooleanField(default=False, verbose_name='Запрос обработан'),
        ),
    ]
