# Generated by Django 5.0.4 on 2025-10-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_callrequest_is_called'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricerequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=80, verbose_name='Номер телефона')),
                ('qwestion', models.TextField(max_length=800, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заказ оптового прайса',
                'verbose_name_plural': 'Заказы оптового прайса',
            },
        ),
    ]
