# Generated by Django 5.0.4 on 2025-10-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_pricerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerequest',
            name='is_called',
            field=models.BooleanField(default=False, verbose_name='Запрос обработан'),
        ),
    ]
