# Generated by Django 5.0.4 on 2025-10-18 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_pricerequest_is_called'),
        ('products', '0015_alter_characteristicsmiddlemodel_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holdmerequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=80, verbose_name='Номер телефона')),
                ('dateandtame', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('is_called', models.BooleanField(default=False, verbose_name='Запрос обработан')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Просьба сообщить о поступлении',
                'verbose_name_plural': 'Просьбы сообщить о поступлении',
            },
        ),
    ]
