# Generated by Django 5.0.4 on 2026-01-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_holdmerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('address', 'Адрес'), ('worktime', 'Время работы'), ('email', 'Email'), ('vk', 'VKontakte'), ('instagram', 'Instagram'), ('other', 'Другое')], default='phone', max_length=20, verbose_name='Тип контакта')),
                ('value', models.CharField(help_text='Введите телефон, ссылку или текст', max_length=255, verbose_name='Значение')),
                ('display_text', models.CharField(blank=True, help_text='Если оставить пустым, будет использовано значение', max_length=255, verbose_name='Текст для отображения')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['order', 'id'],
            },
        ),
    ]
