# Generated by Django 5.0.4 on 2026-01-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
