# Generated by Django 5.0.4 on 2026-01-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fquestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=80, verbose_name='Вопрос')),
                ('abswer', models.CharField(max_length=500, verbose_name='Ответ')),
                ('ranc', models.IntegerField(default=1, verbose_name='Порядок вывода')),
                ('show_in_top', models.BooleanField(default=True, verbose_name='Выводить на странице')),
            ],
            options={
                'verbose_name': 'Частый вопрос',
                'verbose_name_plural': 'Частые вопросы',
            },
        ),
    ]
