# Generated by Django 5.0.4 on 2026-01-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_fquestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fquestions',
            old_name='show_in_top',
            new_name='show',
        ),
    ]
