# Generated by Django 5.0.4 on 2026-01-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_rename_show_in_top_fquestions_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fquestions',
            name='abswer',
            field=models.TextField(max_length=500, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='fquestions',
            name='question',
            field=models.TextField(max_length=80, verbose_name='Вопрос'),
        ),
    ]
