# Generated by Django 5.0.4 on 2026-01-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_alter_fquestions_abswer_alter_fquestions_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fquestions',
            old_name='abswer',
            new_name='answer',
        ),
    ]
