# Generated by Django 5.0.4 on 2026-01-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_rename_abswer_fquestions_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fquestions',
            options={'ordering': ['ranc'], 'verbose_name': 'Частый вопрос', 'verbose_name_plural': 'Частые вопросы'},
        ),
    ]
