# Generated by Django 5.1.2 on 2026-01-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0014_alter_fquestions_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_min', models.TextField(blank=True, max_length=80, verbose_name='Мелкий текст')),
                ('text_big', models.TextField(blank=True, max_length=500, verbose_name='Большой текст')),
                ('text_button', models.CharField(blank=True, max_length=80, verbose_name='Текст кнопки')),
                ('text_link', models.CharField(blank=True, max_length=500, verbose_name='Ссылка кнопки')),
                ('image', models.ImageField(help_text='1980 на 748 пикселей', upload_to='slider_images', verbose_name='Изображение фоновое')),
                ('image_min', models.ImageField(blank=True, help_text='406 на 404 пикселей', upload_to='slider_images', verbose_name='Изображение маленькое')),
                ('ranc', models.IntegerField(default=1, verbose_name='Порядок вывода')),
                ('show', models.BooleanField(default=True, verbose_name='Выводить на баннер?')),
            ],
            options={
                'verbose_name': 'Слайд баннера на главной',
                'verbose_name_plural': 'Слайды баннера на главной',
                'ordering': ['ranc'],
            },
        ),
    ]
