# Generated by Django 5.0.4 on 2026-01-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0015_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='text_button',
            field=models.CharField(blank=True, max_length=80, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка кнопки'),
        ),
    ]
