# Generated by Django 5.1.2 on 2026-02-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0015_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('delivery', 'доставка'), ('uslovija_vozvrata', 'условия возврата'), ('home', 'главная')], max_length=20, verbose_name='Страница')),
                ('title', models.CharField(max_length=180, verbose_name='title')),
                ('description', models.TextField(max_length=500, verbose_name='description (описание страницы)')),
                ('span', models.TextField(blank=True, max_length=500, verbose_name='Заголовок верхний')),
                ('h1', models.TextField(blank=True, max_length=500, verbose_name='Заголовок главный')),
            ],
            options={
                'verbose_name': 'Настройка страницы',
                'verbose_name_plural': 'Настройки страниц',
            },
        ),
        migrations.CreateModel(
            name='ImageTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranc', models.IntegerField(default=1, verbose_name='Порядок вывода')),
                ('h2', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=2500, verbose_name='Текст')),
                ('image', models.ImageField(help_text='370px X 400px', upload_to='pagesimages', verbose_name='Изображение')),
                ('alt', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Небольшое описание изображения для СЕО')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_blocks', to='coreapp.pages', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Блок с текстом и изображением',
                'verbose_name_plural': 'Блоки с текстом и изображением',
            },
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranc', models.IntegerField(default=1, verbose_name='Порядок вывода')),
                ('image', models.ImageField(blank=True, help_text='750px X 495px', upload_to='pagesimages', verbose_name='Изображение')),
                ('alt', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Небольшое описание изображения для СЕО')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_blocks', to='coreapp.pages', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Блок с изображением',
                'verbose_name_plural': 'Блоки с изображением',
            },
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranc', models.IntegerField(default=1, verbose_name='Порядок вывода')),
                ('h2', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Текст')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_blocks', to='coreapp.pages', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Блок с текстом',
                'verbose_name_plural': 'Блоки с текстом',
            },
        ),
        migrations.CreateModel(
            name='VideoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranc', models.IntegerField(default=1, verbose_name='Порядок вывода')),
                ('h2', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Заголовок')),
                ('frame', models.TextField(blank=True, help_text='Обязательно заменить на значения width="100%" height="400"', max_length=2500, null=True, verbose_name='Код видео')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_blocks', to='coreapp.pages', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Блок с видео',
                'verbose_name_plural': 'Блоки с видео',
            },
        ),
    ]
