# Generated by Django 5.0.4 on 2026-01-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0016_pages_imagetextblock_imageblock_textblock_videoblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='contact_type',
            new_name='page',
        ),
    ]
