# Generated by Django 5.0.4 on 2026-01-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0017_rename_contact_type_pages_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageblock',
            options={'verbose_name': 'Блок с изображением', 'verbose_name_plural': 'Блоки с изображением'},
        ),
        migrations.AlterModelOptions(
            name='imagetextblock',
            options={'verbose_name': 'Блок с текстом и изображением', 'verbose_name_plural': 'Блоки с текстом и изображением'},
        ),
        migrations.AlterModelOptions(
            name='textblock',
            options={'verbose_name': 'Блок с текстом', 'verbose_name_plural': 'Блоки с текстом'},
        ),
        migrations.AlterModelOptions(
            name='videoblock',
            options={'verbose_name': 'Блок с видео', 'verbose_name_plural': 'Блоки с видео'},
        ),
        migrations.RemoveField(
            model_name='imageblock',
            name='page',
        ),
        migrations.RemoveField(
            model_name='imageblock',
            name='ranc',
        ),
        migrations.RemoveField(
            model_name='imagetextblock',
            name='page',
        ),
        migrations.RemoveField(
            model_name='imagetextblock',
            name='ranc',
        ),
        migrations.RemoveField(
            model_name='textblock',
            name='page',
        ),
        migrations.RemoveField(
            model_name='textblock',
            name='ranc',
        ),
        migrations.RemoveField(
            model_name='videoblock',
            name='page',
        ),
        migrations.RemoveField(
            model_name='videoblock',
            name='ranc',
        ),
        migrations.AlterField(
            model_name='imagetextblock',
            name='image',
            field=models.ImageField(help_text='370px X 400px', upload_to='pagesimages', verbose_name='Изображение'),
        ),
    ]
