# Generated by Django 5.0.4 on 2026-01-25 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0018_alter_imageblock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageblock',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_blocks', to='coreapp.pages', verbose_name='Страница'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageblock',
            name='ranc',
            field=models.IntegerField(default=1, verbose_name='Порядок вывода'),
        ),
        migrations.AddField(
            model_name='imagetextblock',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_blocks', to='coreapp.pages', verbose_name='Страница'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagetextblock',
            name='ranc',
            field=models.IntegerField(default=1, verbose_name='Порядок вывода'),
        ),
        migrations.AddField(
            model_name='textblock',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_blocks', to='coreapp.pages', verbose_name='Страница'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textblock',
            name='ranc',
            field=models.IntegerField(default=1, verbose_name='Порядок вывода'),
        ),
        migrations.AddField(
            model_name='videoblock',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_blocks', to='coreapp.pages', verbose_name='Страница'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoblock',
            name='ranc',
            field=models.IntegerField(default=1, verbose_name='Порядок вывода'),
        ),
    ]
