# Generated by Django 5.0.4 on 2026-01-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0019_imageblock_page_imageblock_ranc_imagetextblock_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='desctiption',
            new_name='description',
        ),
    ]
