# Generated by Django 5.0.4 on 2026-02-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0020_rename_desctiption_pages_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetextblock',
            name='h2',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='imagetextblock',
            name='side',
            field=models.CharField(choices=[('left', 'слева'), ('right', 'справа')], default='right', max_length=20, verbose_name='Положение изображения'),
        ),
    ]
