# Generated by Django 5.0.4 on 2026-02-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0021_imagetextblock_h2_imagetextblock_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoblock',
            name='h2',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='Заголовок'),
        ),
    ]
