# Generated by Django 5.0.4 on 2026-02-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0022_videoblock_h2'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageblock',
            name='alt',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='Небольшое описание изображения для СЕО'),
        ),
    ]
