# Generated by Django 5.0.4 on 2026-02-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0024_imagetextblock_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetextblock',
            name='side',
        ),
    ]
