# Generated by Django 5.0.4 on 2026-03-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True, verbose_name='slug для url'),
            preserve_default=False,
        ),
    ]
