# Generated by Django 5.0.4 on 2026-03-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0003_alter_article_options_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='about',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Краткое описание'),
        ),
    ]
