# Generated by Django 5.0.4 on 2026-03-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0004_article_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True, default='2024-01-01', verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videoblock',
            name='h2',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Заголовок'),
        ),
    ]
